spring.application.name=app
spring.datasource.url=jdbc:postgresql://localhost:5433/ai_chat_app
spring.datasource.username=postgres
spring.datasource.password=Postgres@123
spring.datasource.*
spring.jpa.hibernate.ddl-auto= update
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:3b

